#pragma once

namespace glad {
    enum class FramebufferAttachment : GLenum {
        ColorAttachment0       = GL_COLOR_ATTACHMENT0,
        ColorAttachment1       = GL_COLOR_ATTACHMENT1,
        ColorAttachment2       = GL_COLOR_ATTACHMENT2,
        ColorAttachment3       = GL_COLOR_ATTACHMENT3,
        ColorAttachment4       = GL_COLOR_ATTACHMENT4,
        ColorAttachment5       = GL_COLOR_ATTACHMENT5,
        ColorAttachment6       = GL_COLOR_ATTACHMENT6,
        ColorAttachment7       = GL_COLOR_ATTACHMENT7,
        ColorAttachment8       = GL_COLOR_ATTACHMENT8,
        ColorAttachment9       = GL_COLOR_ATTACHMENT9,
        ColorAttachment10      = GL_COLOR_ATTACHMENT10,
        ColorAttachment11      = GL_COLOR_ATTACHMENT11,
        ColorAttachment12      = GL_COLOR_ATTACHMENT12,
        ColorAttachment13      = GL_COLOR_ATTACHMENT13,
        ColorAttachment14      = GL_COLOR_ATTACHMENT14,
        ColorAttachment15      = GL_COLOR_ATTACHMENT15,
        ColorAttachment16      = GL_COLOR_ATTACHMENT16,
        ColorAttachment17      = GL_COLOR_ATTACHMENT17,
        ColorAttachment18      = GL_COLOR_ATTACHMENT18,
        ColorAttachment19      = GL_COLOR_ATTACHMENT19,
        ColorAttachment20      = GL_COLOR_ATTACHMENT20,
        ColorAttachment21      = GL_COLOR_ATTACHMENT21,
        ColorAttachment22      = GL_COLOR_ATTACHMENT22,
        ColorAttachment23      = GL_COLOR_ATTACHMENT23,
        ColorAttachment24      = GL_COLOR_ATTACHMENT24,
        ColorAttachment25      = GL_COLOR_ATTACHMENT25,
        ColorAttachment26      = GL_COLOR_ATTACHMENT26,
        ColorAttachment27      = GL_COLOR_ATTACHMENT27,
        ColorAttachment28      = GL_COLOR_ATTACHMENT28,
        ColorAttachment29      = GL_COLOR_ATTACHMENT29,
        ColorAttachment30      = GL_COLOR_ATTACHMENT30,
        ColorAttachment31      = GL_COLOR_ATTACHMENT31,
        DepthAttachment        = GL_DEPTH_ATTACHMENT,
        StencilAttachment      = GL_STENCIL_ATTACHMENT,
        DepthStencilAttachment = GL_DEPTH_STENCIL_ATTACHMENT,
    };
}
